sudo: false

language: php

matrix:
  include:
    - php: 5.5
      env:
        - COMPOSER_FLAGS="--prefer-lowest --prefer-dist --no-interaction"
    - php: 5.6
      env:
        - COMPOSER_FLAGS="--prefer-lowest --prefer-dist --no-interaction"
    - php: 7.0
      env:
        - COMPOSER_FLAGS="--prefer-dist --no-interaction"
    - php: 7.1
      env:
        - COMPOSER_FLAGS="--prefer-dist --no-interaction"

before_script:
  - composer self-update
  - composer update $COMPOSER_FLAGS
  - mkdir data
  - php bin/testconsole.php jackalope:init:dbal --force

script: 
  - php ./vendor/bin/phpunit
  # run the benchmarks with 1 iteration and 1 rev each to ensure that they work.
  - php ./vendor/bin/phpbench run --progress=dots --iterations=1 --revs=1

notifications:
  slack:
    secure: "Gd3/1e0pBKvJv1UhWpBkWijJpmSWlarg6uPBJO0h4z1IpkZjd++jOjhmOQ7n+yMfuapQuJTcVOK0yIWu7orJoGAKFkBlMEIrLk1xMAG9phjjMLUO0FWgcQ3eVW5mTyfMBtClz4OL5wXckw17ohtXHDK8qnI0Hz9Qj8Rqgf2OZhM="
